In [1]:
import pandas as pd
import os
from datetime import datetime

In [2]:
# Carregando os arquivos.

FOLDER = f'{os.getcwd()}/archive'
customers_dataset = pd.read_csv(f'{FOLDER}/olist_customers_dataset.csv')
geolocation_dataset = pd.read_csv(f'{FOLDER}/olist_geolocation_dataset.csv')
order_items_dataset = pd.read_csv(f'{FOLDER}/olist_order_items_dataset.csv')
order_payments_dataset = pd.read_csv(f'{FOLDER}/olist_order_payments_dataset.csv')
order_reviews_dataset = pd.read_csv(f'{FOLDER}/olist_order_reviews_dataset.csv')
orders_dataset = pd.read_csv(f'{FOLDER}/olist_orders_dataset.csv')
products_dataset = pd.read_csv(f'{FOLDER}/olist_products_dataset.csv')
sellers_dataset = pd.read_csv(f'{FOLDER}/olist_sellers_dataset.csv')
product_category_name_translation = pd.read_csv(f'{FOLDER}/product_category_name_translation.csv')

In [3]:
# Juntando os arquivos em um s√≥ chamado 'final_dataframe'

order_items_products = pd.merge(order_items_dataset,products_dataset,on='product_id')
order_items_products_sellers = pd.merge(order_items_products,sellers_dataset,on='seller_id')
two_order_items_products_sellers = pd.merge(order_items_products_sellers,orders_dataset,on='order_id')
two_order_items_products_sellers_customer = pd.merge(two_order_items_products_sellers,customers_dataset,on='customer_id')
two_order_items_products_sellers_customer_reviews = pd.merge(two_order_items_products_sellers_customer,order_reviews_dataset,on='order_id')
final_dataframe = pd.merge(two_order_items_products_sellers_customer_reviews,order_payments_dataset,on='order_id')

# Colocando o mapeamento das categorias de produto em ingles 

mapping = dict(zip(product_category_name_translation['product_category_name'].tolist(),product_category_name_translation['product_category_name_english'].tolist()))
final_dataframe['product_category_name'] = final_dataframe['product_category_name'].map(mapping)

In [4]:
# Tipos de dados das colunas
final_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117329 entries, 0 to 117328
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117329 non-null  object
 1   order_item_id                  117329 non-null  int64
 2   product_id                     117329 non-null  object
 3   seller_id                      117329 non-null  object
 4   shipping_limit_date            117329 non-null  object
 5   price                          117329 non-null  float64
 6   freight_value                  117329 non-null  float64
 7   product_category_name          115609 non-null  object
 8   product_name_lenght            115634 non-null  float64
 9   product_description_lenght     115634 non-null  float64
 10  product_photos_qty             115634 non-null  float64
 11  product_weight_g               117309 non-null  float64
 12  product_length_cm              117309 non-null  float64
 13  product_height_cm              117309 non-null  float64
 14  product_width_cm               117309 non-null  float64
 15  seller_zip_code_prefix         117329 non-null  int64
 16  seller_city                    117329 non-null  object
 17  seller_state                   117329 non-null  object
 18  customer_id                    117329 non-null  object
 19  order_status                   117329 non-null  object
 20  order_purchase_timestamp       117329 non-null  object
 21  order_approved_at              117314 non-null  object
 22  order_delivered_carrier_date   116094 non-null  object
 23  order_delivered_customer_date  114858 non-null  object
 24  order_estimated_delivery_date  117329 non-null  object
 25  customer_unique_id             117329 non-null  object
 26  customer_zip_code_prefix       117329 non-null  int64
 27  customer_city                  117329 non-null  object
 28  customer_state                 117329 non-null  object
 29  review_id                      117329 non-null  object
 30  review_score                   117329 non-null  int64
 31  review_comment_title           13892 non-null   object
 32  review_comment_message         49679 non-null   object
 33  review_creation_date           117329 non-null  object
 34  review_answer_timestamp        117329 non-null  object
 35  payment_sequential             117329 non-null  int64
 36  payment_type                   117329 non-null  object
 37  payment_installments           117329 non-null  int64
 38  payment_value                  117329 non-null  float64
dtypes: float64(10), int64(6), object(23)
memory usage: 34.9+ MB

In [5]:
final_dataframe.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,...,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,payment_sequential,payment_type,payment_installments,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,cool_stuff,58.0,598.0,...,97ca439bc427b48bc1cd7177abe71365,5,NaN,"Perfeito, produto entregue antes do combinado.",2017-09-21 00:00:00,2017-09-22 10:57:03,1,credit_card,2,72.19
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,cool_stuff,58.0,598.0,...,b11cba360bbe71410c291b764753d37f,5,NaN,"lannister como sempre, entregou certinho e den...",2017-07-14 00:00:00,2017-07-17 12:50:07,1,boleto,1,73.86
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,cool_stuff,58.0,598.0,...,af01c4017c5ab46df6cc810e069e654a,4,super recomendo,carrinho muito bonito,2018-06-05 00:00:00,2018-06-06 21:41:12,1,credit_card,2,83.23
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,cool_stuff,58.0,598.0,...,8304ff37d8b16b57086fa283fe0c44f8,5,NaN,NaN,2017-08-10 00:00:00,2017-08-13 03:35:17,1,credit_card,3,75.07
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,cool_stuff,58.0,598.0,...,426f43a82185969503fb3c86241a9535,5,NaN,NaN,2017-08-25 00:00:00,2017-08-28 00:51:18,1,credit_card,4,72.19

In [6]:
print('Original ', final_dataframe.shape)
final_dataframe = final_dataframe.drop_duplicates(subset=['order_id','order_purchase_timestamp','product_id','customer_unique_id','review_comment_message'])
print('Depois de dropar as colunas duplicadas ', final_dataframe.shape)

Original  (117329, 39)
Depois de dropar as colunas duplicadas  (101878, 39)

In [7]:
#Dropando colunas de ID
final_dataframe.drop(['order_id','product_id','seller_id','customer_unique_id'], axis=1, inplace=True)

# Nome das colunas
print(final_dataframe.columns)

Index(['order_item_id', 'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'customer_id',
       'order_status', 'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'review_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value'],
      dtype='object')

In [8]:
# Verificando valores nulos
final_dataframe.isnull().sum()

order_item_id                        0
shipping_limit_date                  0
price                                0
freight_value                        0
product_category_name             1476
product_name_lenght               1454
product_description_lenght        1454
product_photos_qty                1454
product_weight_g                    16
product_length_cm                   16
product_height_cm                   16
product_width_cm                    16
seller_zip_code_prefix               0
seller_city                          0
seller_state                         0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   14
order_delivered_carrier_date      1015
order_delivered_customer_date     2136
order_estimated_delivery_date        0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
review_id                            0
review_score                         0
review_comment_title             89829
review_comment_message           59338
review_creation_date                 0
review_answer_timestamp              0
payment_sequential                   0
payment_type                         0
payment_installments                 0
payment_value                        0
dtype: int64

In [9]:
#Dropando linhas nulas de data
final_dataframe = final_dataframe.dropna(subset=['shipping_limit_date','order_purchase_timestamp','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date'])

In [10]:
#Calculando diferen√ßas de tempo de entrega. Isso pode influenciar nas avalia√ß√µes finais
intermediate_time = final_dataframe['order_delivered_customer_date'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date()) - final_dataframe['order_purchase_timestamp'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date())
final_dataframe['purchase-delivery difference'] = intermediate_time.apply(lambda x:x.days)

intermediate_time = final_dataframe['order_estimated_delivery_date'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date()) - final_dataframe['order_delivered_customer_date'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date())
final_dataframe['estimated-actual delivery difference'] = intermediate_time.apply(lambda x:x.days)

In [11]:
final_dataframe.to_csv('df_unificado.csv', index=False)